[hrpsys_choreonoid_tutorials][TABLIS] edit choreonoid environment file
start-jsk/rtmros_choreonoid pull request #368
Opened 2022-07-22 02:30 UTC by kirohy

TABLISの腕の関節追加に伴って，関節角の初期値を追加しました．

2022-07-22 02:49 UTC, Naoki-Hiraoka requested changes
モデルから力センサを除いたので、
```
rtmlaunch  hrpsys_choreonoid_tutorials tablis_choreonoid.launch 
```
や
```
rtmlaunch  hrpsys_choreonoid_tutorials tablis_base_choreonoid.launch 
```
がエラーになるようになりました。

力センサを必要とするRTCを起動しないようにすることで、これらをエラー無く立ち上げられるようにしました。

https://github.com/kirohy/rtmros_choreonoid/pull/1

2022-07-22 03:27 UTC, Naoki-Hiraoka commented
訂正です。

モデルからは力センサを除いていなくて、

```
rtmlaunch  hrpsys_choreonoid_tutorials tablis_choreonoid.launch 
```
や
```
rtmlaunch  hrpsys_choreonoid_tutorials tablis_base_choreonoid.launch 
```
がエラーになる原因は、https://github.com/start-jsk/rtmros_tutorials/pull/604 で.confファイルのend_effectorsにelbowを追加していたため、Stabilizerがエラーになっていたためでした。
https://github.com/kirohy/rtmros_tutorials/blob/5dd1038e9bdb6431a02cae6ba248c462f518348a/hrpsys_ros_bridge_tutorials/CMakeLists.txt#L461

これを直すためには、
* .confファイルのend_effectorsからelbowを抜く
* elbowがあるとエラーになるRTCを起動しない https://github.com/kirohy/rtmros_choreonoid/pull/1

のどちらかを行う必要があります。

@kirohy と相談し、@kirohy の実験で.confファイルのend_effectorsにelbowがあると便利なことと、elbowがあるとエラーになるStabilizerなどのRTCは当面TABLISで使う予定がないことから、後者を行うことにしました。

@kirohy 後でhttps://github.com/kirohy/rtmros_choreonoid/pull/1 の変更を取り入れていただけますでしょうか。

2022-07-22 04:01 UTC, Naoki-Hiraoka approved these changes
```
rtmlaunch  hrpsys_choreonoid_tutorials tablis_choreonoid.launch 
```
```
rtmlaunch  hrpsys_choreonoid_tutorials tablis_base_choreonoid.launch 
```

が立ち上がることを確認しました。

mergeする場合はこれら4つのPull Requestを同時にお願いいたします。
https://github.com/start-jsk/rtmros_hrp2/pull/601
https://github.com/start-jsk/rtmros_tutorials/pull/604
https://github.com/jsk-ros-pkg/trans_system/pull/808
https://github.com/start-jsk/rtmros_choreonoid/pull/368

2022-07-22 09:14 UTC, kirohy commented
@k-okada @kindsenior これらの変更に問題なければmergeしていただけないでしょうか

2022-07-22 09:44 UTC, k-okada commented
https://github.com/start-jsk/rtmros_choreonoid/runs/7461868201?check_suite_focus=true
で以下のようなエラーがでていますが大丈夫でしょうか？
```
2022-07-22T04:32:13.9791233Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423112146]: Sensor gsensor is attached to BODY base_imu 0[0m
2022-07-22T04:32:13.9791239Z 
2022-07-22T04:32:13.9791346Z                                                                                 
2022-07-22T04:32:13.9791778Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423190448]: Sensor gyrometer is attached to BODY base_imu 0[0m
2022-07-22T04:32:13.9791784Z 
2022-07-22T04:32:13.9791895Z                                                                                 
2022-07-22T04:32:13.9792265Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423283149]: Sensor CHEST_CAMERA is attached to CHEST_LINK2 base_pinhole_camera 2[0m
2022-07-22T04:32:13.9792272Z 
2022-07-22T04:32:13.9792276Z 
2022-07-22T04:32:13.9792385Z                                                                                 
2022-07-22T04:32:13.9792756Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423359251]: Sensor HEAD_LEFT_CAMERA is attached to HEAD_LINK1 base_pinhole_camera 0[0m
2022-07-22T04:32:13.9792762Z 
2022-07-22T04:32:13.9792858Z                                                                                 
2022-07-22T04:32:13.9793228Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423451952]: Sensor HEAD_RIGHT_CAMERA is attached to HEAD_LINK1 base_pinhole_camera 1[0m
2022-07-22T04:32:13.9793237Z 
2022-07-22T04:32:13.9793242Z 
2022-07-22T04:32:13.9793440Z                                                                                 
2022-07-22T04:32:13.9793802Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423640856]: Sensor lhsensor is attached to LARM_LINK7 base_force6d 3[0m
2022-07-22T04:32:13.9793808Z 
2022-07-22T04:32:13.9793918Z                                                                                 
2022-07-22T04:32:13.9794278Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423686857]: Sensor LARM_CAMERA is attached to LARM_LINK7 base_pinhole_camera 5[0m
2022-07-22T04:32:13.9794283Z 
2022-07-22T04:32:13.9794394Z                                                                                 
2022-07-22T04:32:13.9794753Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423745458]: Sensor LARM_CAMERA_N is attached to LARM_LINK7 base_pinhole_camera 6[0m
2022-07-22T04:32:13.9794762Z 
2022-07-22T04:32:13.9794870Z                                                                                 
2022-07-22T04:32:13.9795215Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423883560]: Sensor lfsensor is attached to LLEG_LINK5 base_force6d 1[0m
2022-07-22T04:32:13.9795221Z 
2022-07-22T04:32:13.9795331Z                                                                                 
2022-07-22T04:32:13.9795921Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.423940361]: Sensor HEAD_RANGE is attached to RANGE_LINK base_laser1d 0[0m
2022-07-22T04:32:13.9795942Z 
2022-07-22T04:32:13.9795948Z 
2022-07-22T04:32:13.9796056Z                                                                                 
2022-07-22T04:32:13.9796443Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.424143965]: Sensor rhsensor is attached to RARM_LINK7 base_force6d 2[0m
2022-07-22T04:32:13.9796450Z 
2022-07-22T04:32:13.9796455Z 
2022-07-22T04:32:13.9796581Z                                                                                 
2022-07-22T04:32:13.9796992Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.424740676]: Sensor RARM_CAMERA is attached to RARM_LINK7 base_pinhole_camera 3[0m
2022-07-22T04:32:13.9796999Z 
2022-07-22T04:32:13.9797004Z 
2022-07-22T04:32:13.9797128Z                                                                                 
2022-07-22T04:32:13.9797541Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.425215385]: Sensor RARM_CAMERA_N is attached to RARM_LINK7 base_pinhole_camera 4[0m
2022-07-22T04:32:13.9797547Z 
2022-07-22T04:32:13.9797553Z 
2022-07-22T04:32:13.9797676Z                                                                                 
2022-07-22T04:32:13.9798066Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.425694294]: Sensor rfsensor is attached to RLEG_LINK5 base_force6d 0[0m
2022-07-22T04:32:13.9798072Z 
2022-07-22T04:32:13.9798078Z 
2022-07-22T04:32:13.9798303Z                                                                                 
2022-07-22T04:32:13.9798683Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.467257058]: Sensor gsensor is attached to BODY base_imu 0[0m
2022-07-22T04:32:13.9798689Z 
2022-07-22T04:32:13.9798695Z 
2022-07-22T04:32:13.9798819Z                                                                                 
2022-07-22T04:32:13.9799190Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.467922270]: Sensor gyrometer is attached to BODY base_imu 0[0m
2022-07-22T04:32:13.9799196Z 
2022-07-22T04:32:13.9799201Z 
2022-07-22T04:32:13.9799536Z                                                                                 
2022-07-22T04:32:13.9799921Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.468440980]: Sensor CHEST_CAMERA is attached to CHEST_LINK2 base_pinhole_camera 2[0m
2022-07-22T04:32:13.9799927Z 
2022-07-22T04:32:13.9799932Z 
2022-07-22T04:32:13.9800051Z                                                                                 
2022-07-22T04:32:13.9800645Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.468859687]: Sensor HEAD_LEFT_CAMERA is attached to HEAD_LINK1 base_pinhole_camera 0[0m
2022-07-22T04:32:13.9800656Z 
2022-07-22T04:32:13.9800679Z 
2022-07-22T04:32:13.9800906Z                                                                                 
2022-07-22T04:32:13.9801532Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.469420198]: Sensor HEAD_RIGHT_CAMERA is attached to HEAD_LINK1 base_pinhole_camera 1[0m
2022-07-22T04:32:13.9801541Z 
2022-07-22T04:32:13.9801546Z 
2022-07-22T04:32:13.9801669Z                                                                                 
2022-07-22T04:32:13.9802057Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.469948907]: Sensor lhsensor is attached to LARM_LINK7 base_force6d 3[0m
2022-07-22T04:32:13.9802063Z 
2022-07-22T04:32:13.9802069Z 
2022-07-22T04:32:13.9802192Z                                                                                 
2022-07-22T04:32:13.9802613Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.470333715]: Sensor LARM_CAMERA is attached to LARM_LINK7 base_pinhole_camera 5[0m
2022-07-22T04:32:13.9802620Z 
2022-07-22T04:32:13.9802625Z 
2022-07-22T04:32:13.9802751Z                                                                                 
2022-07-22T04:32:13.9803162Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.470710621]: Sensor LARM_CAMERA_N is attached to LARM_LINK7 base_pinhole_camera 6[0m
2022-07-22T04:32:13.9803168Z 
2022-07-22T04:32:13.9803173Z 
2022-07-22T04:32:13.9803297Z                                                                                 
2022-07-22T04:32:13.9803898Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.471176830]: Sensor lfsensor is attached to LLEG_LINK5 base_force6d 1[0m
2022-07-22T04:32:13.9803905Z 
2022-07-22T04:32:13.9803909Z 
2022-07-22T04:32:13.9804027Z                                                                                 
2022-07-22T04:32:13.9804506Z [hrpsys_choreonoid_tutorials:make] [33m[ WARN] [1658464323.471565237]: Sensor HEAD_RANGE is attached to RANGE_LINK base_laser1d 0[0m
2022-07-22T04:32:13.9804512Z 
2022-07-22T04:32:13.9804517Z 
2022-07-22T04:32:13.9804625Z                                                                                 
2022-07-2 [...]

2022-07-22 09:59 UTC, Naoki-Hiraoka commented
とりあえずrestartしました。

@kirohy 
このpull requestですが、まだpull requestを出してから日が浅く、他のurata系ユーザーの人でreviewしたいと思っている人がもしいた場合にreviewする時間がないのと、意外とpull requestを出した本人がミスに気付いて直したくなる可能性があるので、週明けくらいまで寝かせたほうが良いのではないかと思います。来週小島先生に対面でお願いしてacceptしてもらい、小島先生が権限があるリポジトリはmergeしてもらい、その後、それ以外のリポジトリについて岡田先生にmentionしてmergeをお願いする流れが良いのではないでしょうか。

そのために、週明けまでにテストを通すことを目指しましょう。

2022-09-16 09:19 UTC, merged

2022-09-16 09:20 UTC, kindsenior commented
テストが通りましたのでマージしました